/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eeceg;

import java.io.File;
import java.math.BigInteger;
import java.nio.file.Files;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;


/**
 *
 * @author Fahziar
 */
public class EECEGForm extends javax.swing.JFrame {

    /**
     * Creates new form EECEGForm
     */
    
    File flPrivateA, flPrivateB, flPublicA, flPublicB;
    
    byte[] plainText, cipherText;
    
    long privateKey;
    
    JFileChooser fc;
    
    public EECEGForm() {
        initComponents();
        
        lblPublicA.setText("");
        lblPrivateA.setText("");
                
        fc = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBx = new javax.swing.JTextField();
        txtBy = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPublicA = new javax.swing.JButton();
        lblPublicA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPrivateA = new javax.swing.JButton();
        lblPrivateA = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnLoadPlain = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPlain = new javax.swing.JTextArea();
        btnSavePlain = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCipher = new javax.swing.JTextArea();
        btnLoadCipher = new javax.swing.JButton();
        btnSaveCipher = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();
        btnGenerateKeys = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elliptic Curve Cryptography El Gamal");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("EEC Properties"));

        jLabel1.setText("a:");

        jLabel2.setText("b:");

        jLabel3.setText("p:");

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });

        jLabel6.setText("B.x:");

        jLabel7.setText("B.y:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtC)
                            .addComponent(txtA)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBx)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Keys"));

        jLabel4.setText("Public    :");

        btnPublicA.setText("Browse");
        btnPublicA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPublicAMouseClicked(evt);
            }
        });

        lblPublicA.setText("jLabel8");

        jLabel5.setText("Private :");

        btnPrivateA.setText("Browse");
        btnPrivateA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrivateAMouseClicked(evt);
            }
        });

        lblPrivateA.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPublicA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPublicA))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrivateA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrivateA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnPublicA)
                    .addComponent(lblPublicA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnPrivateA)
                    .addComponent(lblPrivateA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLoadPlain.setText("Load");
        btnLoadPlain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadPlainMouseClicked(evt);
            }
        });

        txtPlain.setColumns(20);
        txtPlain.setRows(5);
        jScrollPane2.setViewportView(txtPlain);

        btnSavePlain.setText("Save");
        btnSavePlain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSavePlainMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnLoadPlain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSavePlain)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadPlain)
                    .addComponent(btnSavePlain))
                .addGap(7, 7, 7))
        );

        jTabbedPane2.addTab("Plaintext", jPanel4);

        txtCipher.setColumns(20);
        txtCipher.setRows(5);
        jScrollPane1.setViewportView(txtCipher);

        btnLoadCipher.setText("Load");
        btnLoadCipher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadCipherMouseClicked(evt);
            }
        });

        btnSaveCipher.setText("Save");
        btnSaveCipher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveCipherMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnLoadCipher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveCipher)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadCipher)
                    .addComponent(btnSaveCipher))
                .addGap(6, 6, 6))
        );

        jTabbedPane2.addTab("Ciphertext", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));

        btnEncrypt.setText("Encrypt");
        btnEncrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncryptMouseClicked(evt);
            }
        });

        btnDecrypt.setText("Decrypt");
        btnDecrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecryptMouseClicked(evt);
            }
        });

        btnGenerateKeys.setText("Generate Keys");
        btnGenerateKeys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateKeysMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerateKeys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDecrypt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnGenerateKeys)
                .addComponent(btnEncrypt)
                .addComponent(btnDecrypt))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Plaintext");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnPublicAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPublicAMouseClicked
        fc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Public key (.pub)", "pub");
        fc.addChoosableFileFilter(filter);
        fc.showOpenDialog(this);
        
        flPublicA = fc.getSelectedFile();
        lblPublicA.setText(flPublicA.getName());
        
        //TODO: Load public key dari file
        
        fc.setAcceptAllFileFilterUsed(true);
        fc.removeChoosableFileFilter(filter);
    }//GEN-LAST:event_btnPublicAMouseClicked

    private void btnPrivateAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrivateAMouseClicked
        fc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Private key (.pri)", "pri");
        fc.addChoosableFileFilter(filter);
        fc.showOpenDialog(this);
        
        flPrivateA = fc.getSelectedFile();
        lblPrivateA.setText(flPrivateA.getName());
        
        try 
        {
           privateKey = Long.parseLong(FileUtils.readLines(fc.getSelectedFile()).get(0));
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cannot open file");
        }
        
        fc.setAcceptAllFileFilterUsed(true);
        fc.removeChoosableFileFilter(filter);
    }//GEN-LAST:event_btnPrivateAMouseClicked

    private void btnLoadPlainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadPlainMouseClicked
        fc.showOpenDialog(this);
        
        File f = fc.getSelectedFile();
        
        try {
            plainText = Files.readAllBytes(f.toPath());
            txtPlain.setText(new String(plainText, "UTF-8"));
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cannot open file");
        }
    }//GEN-LAST:event_btnLoadPlainMouseClicked

    private void btnLoadCipherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadCipherMouseClicked
        fc.showOpenDialog(this);
        
        File f = fc.getSelectedFile();
        
        try {
            cipherText= Files.readAllBytes(f.toPath());
            txtCipher.setText(HexConvert.toHexFromBytes(cipherText));
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cannot open file");
        }
    }//GEN-LAST:event_btnLoadCipherMouseClicked

    private void btnSavePlainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavePlainMouseClicked
        fc.showSaveDialog(this);
        
        File f  = fc.getSelectedFile();
        
        try
        {
            FileUtils.writeByteArrayToFile(f, plainText);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cannot open file");
        }
    }//GEN-LAST:event_btnSavePlainMouseClicked

    private void btnSaveCipherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveCipherMouseClicked
        fc.showSaveDialog(this);
        
        File f  = fc.getSelectedFile();
        
        try
        {
            FileUtils.writeByteArrayToFile(f, cipherText);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cannot open file");
        }
    }//GEN-LAST:event_btnSaveCipherMouseClicked

    private void btnGenerateKeysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateKeysMouseClicked
        //Generate key
        privateKey = new BigInteger (63, new Random()).longValueExact();
        
        fc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Private key (.pri)", "pri");
        fc.addChoosableFileFilter(filter);
        fc.showSaveDialog(this);
        
        //Save private key
        File out = fc.getSelectedFile();
        if (out.getName().lastIndexOf(".") == -1)
        {
            out = new File(out.getParentFile(), out.getName() + ".pri");
        } else if (out.getName().substring(out.getName().lastIndexOf("."),out.getName().length()).equalsIgnoreCase("pri"))
        {
            out = new File(out.getParentFile(), out.getName() + ".pri");
        }
        
        try {
            FileUtils.writeStringToFile(out, String.valueOf(privateKey), "UTF-8");
        } catch (Exception e)
        {
            
        }
        
        //Save public key
        fc.removeChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("Public key (.pub)", "pub");
        fc.addChoosableFileFilter(filter);
        fc.showSaveDialog(this);
        
        if (out.getName().lastIndexOf(".") == -1)
        {
            out = new File(out.getParentFile(), out.getName() + ".pub");
        } else if (out.getName().substring(out.getName().lastIndexOf("."),out.getName().length()).equalsIgnoreCase("pri"))
        {
            out = new File(out.getParentFile(), out.getName() + ".pub");
        }
        
        try {
            //TODO: Save public key
        } catch (Exception e)
        {
            
        }
        
        fc.removeChoosableFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(true);
    }//GEN-LAST:event_btnGenerateKeysMouseClicked

    private void btnEncryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncryptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncryptMouseClicked

    private void btnDecryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecryptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecryptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EECEGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EECEGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EECEGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EECEGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EECEGForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnGenerateKeys;
    private javax.swing.JButton btnLoadCipher;
    private javax.swing.JButton btnLoadPlain;
    private javax.swing.JButton btnPrivateA;
    private javax.swing.JButton btnPublicA;
    private javax.swing.JButton btnSaveCipher;
    private javax.swing.JButton btnSavePlain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblPrivateA;
    private javax.swing.JLabel lblPublicA;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtBx;
    private javax.swing.JTextField txtBy;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextArea txtCipher;
    private javax.swing.JTextArea txtPlain;
    // End of variables declaration//GEN-END:variables
}
